<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>iris_pxs</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TwainWorker\**" />
    <None Remove="TwainWorker\**" />
    <EmbeddedResource Remove="TwainWorker\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NTwain" Version="3.7.6" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260627" />
  </ItemGroup>

  <Target Name="BuildTwainWorker" BeforeTargets="Build">
    <MSBuild Projects="TwainWorker\TwainWorker.csproj" Targets="Build" Properties="Configuration=$(Configuration);Platform=x86" />
    <ItemGroup>
      <TwainWorkerFiles Include="TwainWorker\bin\x86\$(Configuration)\net8.0-windows\*.*" />
      <TwainWorkerFiles Include="TwainWorker\bin\$(Configuration)\net8.0-windows\*.*" Condition="'@(TwainWorkerFiles)' == ''" />
    </ItemGroup>
    <Copy SourceFiles="@(TwainWorkerFiles)" DestinationFolder="$(OutputPath)TwainWorker\" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="PublishTwainWorker" AfterTargets="Publish">
    <ItemGroup>
      <TwainWorkerFilesPublish Include="TwainWorker\bin\x86\$(Configuration)\net8.0-windows\*.*" />
      <TwainWorkerFilesPublish Include="TwainWorker\bin\$(Configuration)\net8.0-windows\*.*" Condition="'@(TwainWorkerFilesPublish)' == ''" />
    </ItemGroup>
    <Copy SourceFiles="@(TwainWorkerFilesPublish)" DestinationFolder="$(PublishDir)TwainWorker\" SkipUnchangedFiles="true" />
  </Target>

</Project>
